app/cf/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("overtime/", include("overtime.urls", namespace="overtime")),
    path("admin/", admin.site.urls),
]

app/overtime/urls.py
from django.urls import path

from . import views

app_name = "overtime"

urlpatterns = [
    path("", views.TimeSheetListView.as_view(), name="overtime-list"),
    path(
        "detail/<int:pk>/", views.TimeSheetDetailView.as_view(), name="overtime-detail"
    ),
    path("create/", views.TimeSheetCreateView.as_view(), name="overtime-create"),
    path("pdf", views.ViewPDF.as_view(), name="pdf"),
]

app/overtime/models.py
from datetime import datetime, time

from django.db import models
from django.urls import reverse


class JobTitle(models.Model):
    job_title = models.CharField(max_length=25, unique=True)

    def __str__(self) -> str:
        return self.job_title


class Department(models.Model):
    department = models.CharField(max_length=55, unique=True)

    def __str__(self) -> str:
        return self.department


class Employee(models.Model):
    employee = models.CharField(max_length=55, unique=True)
    job_title = models.ForeignKey(
        JobTitle, on_delete=models.CASCADE, blank=True, null=True
    )
    department = models.ForeignKey(
        Department, on_delete=models.CASCADE, blank=True, null=True
    )
    supervisor = models.ForeignKey(
        "Employee",
        related_name="supervisors",
        on_delete=models.CASCADE,
        blank=True,
        null=True,
    )
    salary = models.PositiveSmallIntegerField(default=0)

    @property
    def get_hourly_rate(self):
        return f"{(((self.salary * 12) / 52) / 5) / 8:.2f}"

    def __str__(self) -> str:
        return self.employee


class Multiplier(models.Model):
    multiplier = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return f"{self.multiplier}"


class TimeSheet(models.Model):
    employee = models.ForeignKey(
        Employee, on_delete=models.CASCADE, null=True, blank=True
    )
    date = models.DateField()
    reason = models.TextField("reason for overtime")
    start_time = models.TimeField(default="16:30:00")
    end_time = models.TimeField(default="16:30:00")
    multiplier = models.ForeignKey(Multiplier, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ("-created_at",)

    # def get_absolute_url(self):
    #     return reverse("overtime:overtime-detail", kwargs={"pk": self.pk})

    @property
    def time_diff(self):
        return (
            datetime.strptime(str(self.end_time), "%H:%M:%S")
            - datetime.strptime(str(self.start_time), "%H:%M:%S")
        ).seconds / 3600

    @property
    def get_overtime(self):
        overtime = (float(self.multiplier.multiplier) * float(self.time_diff)) * float(
            self.employee.get_hourly_rate
        )
        return f"{overtime:.2f}"

    def __str__(self):
        return f"{self.get_overtime} hours ({self.time_diff})"


# class Overtime(models.Model):
#     time_sheet = models.ForeignKey(TimeSheet, on_delete=models.CASCADE)

#     def __str__(self):
#         return f"{self.employee.employee}"

app/overtime/forms.py
from django import forms

from .models import TimeSheet


class TimeSheetCreateForm(forms.ModelForm):
    class Meta:
        model = TimeSheet
        fields = "__all__"
        widgets = {
            "date": forms.DateInput(attrs={"type": "date"}),
            "start_time": forms.DateInput(attrs={"type": "time"}),
            "end_time": forms.DateInput(attrs={"type": "time"}),
            "multiplier": forms.RadioSelect(),
            "reason": forms.Textarea(attrs={"rows": 4}),
        }

app/overtime/views.py
from io import BytesIO

from django.http import HttpResponse
from django.shortcuts import render
from django.template.loader import get_template
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import CreateView, DetailView, ListView, UpdateView
from xhtml2pdf import pisa

from .forms import TimeSheetCreateForm
from .models import TimeSheet


def render_to_pdf(template_src, context_dict={}):
    template = get_template(template_src)
    html = template.render(context_dict)
    result = BytesIO()
    pdf = pisa.pisaDocument(BytesIO(html.encode("ISO-8859-1")), result)
    if not pdf.err:
        return HttpResponse(result.getvalue(), content_type="application/pdf")


class ViewPDF(View):
    def get(self, request, *args, **kwargs):
        times = TimeSheet.objects.all().values()
        times_dict = {"times": times}
        pdf = render_to_pdf("overtime/timesheet_list.html", times_dict)
        return HttpResponse(pdf, content_type="application/pdf")


class TimeSheetListView(ListView):
    model = TimeSheet


class TimeSheetCreateView(CreateView):
    model = TimeSheet
    form_class = TimeSheetCreateForm
    
    def get_success_url(self):
        return reverse_lazy('overtime:overtime-list')


class TimeSheetDetailView(DetailView):
    model = TimeSheet

app/templates/base.html
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport"
        content="width=device-width, initial-scale=1">
    <title>
        {% block head_title %}

        {% endblock head_title %}
    </title>

    <link rel="preconnect"
        href="https://fonts.googleapis.com">
    <link rel="preconnect"
        href="https://fonts.gstatic.com"
        crossorigin>
    <link
        href="https://fonts.googleapis.com/css2?family=Montserrat&display=swap"
        rel="stylesheet">
    <link
        href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css"
        rel="stylesheet"
        integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor"
        crossorigin="anonymous">

    <link rel="stylesheet"
        href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.3/font/bootstrap-icons.css">

    <style>
        html,
        body {
            font-family: 'Montserrat', sans-serif;
        }

        td>a {
            cursor: pointer;
        }
    </style>
</head>

<body>

    {% include 'components/header.html' %}

    {% block content %}

    {% endblock content %}

    {% include 'components/footer.html' %}


    <script
        src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2"
        crossorigin="anonymous"></script>
</body>

</html>

app/templates/components/footer.html
<div class="container">
    <footer
        class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
        <div class="col-md-4 d-flex align-items-center">
            <a href="/"
                class="mb-3 me-2 mb-md-0 text-muted text-decoration-none lh-1">
            </a>
            <span class="mb-3 mb-md-0 text-muted">&copy; {% now 'Y' %} <a
                    class="text-dark"
                    href="https://swelanauguste.digital/"
                    target="_blank">kingship</a> </span>
        </div>

        <ul class="nav col-md-4 justify-content-end list-unstyled d-flex">
            <li class="ms-3"><a class="text-muted"
                    href="#"><i class="bi bi-instagram text-warning"></i></a>
            </li>
            <li class="ms-3"><a class="text-muted"
                    href="#"><i class="bi bi-twitter text-info"></i>
                </a></li>
            <li class="ms-3"><a class="text-muted"
                    href="#"><i class="bi bi-facebook text-primary"></i></a>
            </li>
        </ul>
    </footer>
</div>

app/templates/components/header.html
<div class="container">
    <header
        class="d-flex flex-wrap justify-content-center py-3 mb-4 border-bottom">
        <a href="/"
            class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-dark text-decoration-none">
            <span class="fs-4">Online Forms</span>
        </a>

        <ul class="nav nav-pills">
            <li class="nav-item"><a href="{% url 'overtime:overtime-list' %}"
                    class="nav-link text-dark"
                    aria-current="page">Overtime</a></li>
            <!-- <li class="nav-item"><a href="#"
                    class="nav-link">Features</a></li> -->
            <!-- <li class="nav-item"><a href="#"
                    class="nav-link">Pricing</a></li>
            <li class="nav-item"><a href="#"
                    class="nav-link">FAQs</a></li>
            <li class="nav-item"><a href="#"
                    class="nav-link">About</a></li> -->
        </ul>
    </header>
</div>

app/templates/overtime/timesheet_form.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block head_title %}

{% endblock head_title %}



{% block content %}
<div class="container py-3">
    <div class="row">
        <div class="col-lg-3">
            <h1>Add overtime</h1>
            <hr>
        </div>
        <div class="col">
            <div class="container py-3">
                <form class="col-lg-8 border p-4 shadow rounded-4"
                    action=""
                    method="post">
                    {% csrf_token %}
                    {{form|crispy}}
                    <div class="my-3 text-end">
                        <button class="btn btn-sm btn-outline-dark px-5"
                            type="submit">Post</button>
                    </div>
                </form>
            </div>
        </div>
    </div>


</div>
{% endblock content %}

app/templates/overtime/timesheet_list.html
{% extends 'base.html' %}


{% block head_title %}
Overtime
{% endblock head_title %}


{% block content %}
<div class="container py-3">
    <h1>Overtime</h1>
    <hr>
    <div class="container py-3">
        <ul class="nav justify-content-end">
            <li class="nav-item">
                <a class="nav-link text-dark"
                    href="{% url 'overtime:overtime-create' %}"><i class="bi bi-calendar-plus fs-3 text-success"></i></a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-dark"
                    href="#"><i class="bi bi-calendar-date fs-3 text-warning"></i></a>
            </li>
        </ul>
        <hr>
    </div>
    <div class="container px-5">
        <div class="table-responsive">
            <table class="table table-sm table-hover">
                <tbody>
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Date</th>
                            <th>Reason</th>
                            <th>Hours</th>
                            <th colspan="2">Multiplier</th>
                        </tr>
                    </thead>
                    {% for object in object_list %}
                    <tr>
                        <th scope="row">{{ forloop.counter }}</th>
                        <td>{{object.date}}</td>
                        <td>{{object.reason}}</td>
                        <td>{{object.time_diff}}</td>
                        <td>{{object.multiplier}}</td>
                        <td class="">
                            <a class="text-primary text-decoration-none">
                                <i class="bi bi-info-square border-0"
                                    data-bs-toggle="modal"
                                    data-bs-target="#exampleModal_{{object.pk}}"></i>
                            </a>
                            <a class="mx-2" href="#"><i class="bi bi-pencil text-warning"></i></a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>


{% for object in object_list %}


<!-- Modal -->
<div class="modal fade"
    id="exampleModal_{{object.pk}}"
    tabindex="-1"
    aria-labelledby="exampleModalLabel"
    aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title"
                    id="exampleModalLabel">{{object.employee}}</h5>
                <button type="button"
                    class="btn-close"
                    data-bs-dismiss="modal"
                    aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div class="table-responsive">
                    <table class="table table-sm">
                        <tbody>
                            <thead>
                                <tr>
                                    <th>Date</th>
                                    <th>Reason</th>
                                    <th>Hours</th>
                                    <th>Multiplier</th>
                                    <th>Rate</th>
                                    <th>Overtime</th>
                                </tr>
                            </thead>
                            <tr>
                                <td>{{object.date}}</td>
                                <td>{{object.reason}}</td>
                                <td>{{object.time_diff}}</td>
                                <td>{{object.multiplier}}</td>
                                <td>${{object.employee.get_hourly_rate}}</td>
                                <td>${{object.get_overtime}}</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button"
                    class="btn btn-secondary"
                    data-bs-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

{% endfor %}

{% endblock content %}